### ISSUE TITLE
python3 chair_program_from_pc.py test_pc 2307  ; Error(s) in loading state_dict for PCEncoder:

### ISSUE THREAD

**Issue by jiayaozhang** [rkjones4/ShapeAssembly#6]
Hi, so sorry to bother you again.
While I am running this code, I encounter this bug, can you help me to solve this? 

Traceback (most recent call last):
  File "chair_program_from_pc.py", line 80, in <module>
    eval_recon(sys.argv[1],sys.argv[2:])
  File "chair_program_from_pc.py", line 29, in eval_recon
    encoder.load_state_dict(torch.load(point_cloud_encoder))
  File "/home/zhangj0o/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PCEncoder:

![image](https://user-images.githubusercontent.com/38579506/107917174-88fd6a80-6f78-11eb-89ed-9eccc62d2c9e.png)

**Comment by jiayaozhang** [comment]
I would like to post bugs that I have encounter over here.
And hope it may benefit future users. 

I have run the sample_partnet.py which has generated the partnet_pc_sample folder that has a lot of ***.pts.
And compile make_shapeassembly_encodings.py which has generated a folder that contains a lot of **.enc
And when run rain_pc_encoder.py, I encounter the same problem

![image](https://user-images.githubusercontent.com/38579506/108592838-fb0eee80-7380-11eb-926b-3e69d01c5eee.png)

Furthermore, 

I have tried to change here in pc_encoder.py:

from pointnet2_ops_lib.pointnet2_ops.pointnet2_modules import PointnetSAModuleMSG as PointSAModule


and also change the PyTorch version 

![image](https://user-images.githubusercontent.com/38579506/108592909-74a6dc80-7381-11eb-81b2-69c5e72e1894.png)


Also, I have tried to change the PyTorch version =1.3 as it says in the pqp, But still has errors

![image](https://user-images.githubusercontent.com/38579506/108592919-82f4f880-7381-11eb-8b45-908ac974abce.png)

**Comment by jiayaozhang** [comment]
I fixed them all!

I would like to share with others what I have encounter and how I solve this!

first in **train_pc_encoder.py** change the PCEncoder to simpleEncoder(256)
`enc = simplePCEncoder(256)`

add 256 here. 256 means the feat_len
   
Copy **the simplePCEncoder** module to pc_encoder.py 

and in line 103:   
`enc = simplePCEncoder(256).to(device)`

Finally in **chair_program_from_pc.py**
change path to 
`shapeAssembly_decoder = "/home/zhangj0o/ShapeAssembly/code/model_output/pre_chair/models/decoder_119.pt"`
`point_cloud_encoder = "/home/zhangj0o/ShapeAssembly/code/outdir/enc_dict_300.pt"`
`point_cloud_folder = "/home/zhangj0o/ShapeAssembly/code/partnet_pc_sample"`
outdir is what I have got from sample_partnet.py ,make_shapeassembly_encodings.py train_pc_encoder.py


`encoder = simplePCEncoder(256)`  in line 28
